// Using a JavaScript file here because the native TypeScript implementation in newer
// Node.js versions currently causes the following warning:
//
// `(node:8902) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time`

import { parseArgs } from 'node:util';
import { createClient } from '@hey-api/openapi-ts';
import { existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const {
	values: { temp }
} = parseArgs({
	options: {
		temp: {
			type: 'boolean',
			short: 't'
		}
	}
});

const baseDir = process.env.CI_TMP_DIR ?? tmpdir();

// Must match the output location of the backend generator.
const input = join(baseDir, 'backend', 'openapi.json');

// Repository output.
const generatedOutput = 'src/generated';

// Temporary output used by CI.
const tempOutput = join(baseDir, 'frontend', 'generated');

const output = temp ? tempOutput : generatedOutput;

if (!existsSync(input)) {
	console.error(`Input file "${input}" does not exist.`);
	process.exit(1);
}

mkdirSync(output, { recursive: true });

await createClient({
	input,
	output: {
		clean: false,
		path: output,
		header: [
			'// @ts-nocheck',
			'/* eslint-disable */',
			'// This file was generated by @hey-api/openapi-ts. Do not edit.'
		]
	},
	plugins: ['@hey-api/typescript', '@hey-api/sdk', '@hey-api/client-fetch']
});

console.log(output);
