// Using a JavaScript file here because the native TypeScript implementation in newer
// Node.js versions currently causes the following warning:
//
// `(node:8902) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time`

import { parseArgs } from 'node:util';
import { createClient } from '@hey-api/openapi-ts';
import { existsSync, mkdirSync, statSync } from 'node:fs';
import path from 'node:path';

const { values } = parseArgs({
	options: {
		input: {
			type: 'string',
			short: 'i',
			required: true
		},
		output: {
			type: 'string',
			short: 'o',
			required: true
		}
	}
});

const input = path.resolve(values.input);
const output = path.resolve(values.output);

if (!existsSync(input)) {
	console.error(`Input file "${input}" does not exist.`);
	process.exit(2);
}

if (!statSync(input).isFile()) {
	console.error(`Input path '${input}' is not a file.`);
	process.exit(2);
}

mkdirSync(output, { recursive: true });

await createClient({
	input,
	output: {
		clean: false,
		path: output,
		header: [
			'// @ts-nocheck',
			'/* eslint-disable */',
			'// This file was generated by @hey-api/openapi-ts. Do not edit.'
		]
	},
	plugins: ['@hey-api/typescript', '@hey-api/sdk', '@hey-api/client-fetch']
});

console.log(output);
