//
// Tech Stream Conference
// 2026
//
// Generates the frontend API client from the OpenAPI schema.
//

// Using a JavaScript file here because the native TypeScript implementation in newer
// Node.js versions currently causes the following warning:
//
// `(node:8902) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time`

import { createClient } from '@hey-api/openapi-ts';
import { existsSync } from 'node:fs';
import { mkdirSync } from 'node:fs';
import { parseArgs } from 'node:util';
import { statSync } from 'node:fs';
import path from 'node:path';

const { values } = parseArgs({
    options: {
        input: {
            type: 'string',
            short: 'i',
            required: true
        },
        output: {
            type: 'string',
            short: 'o',
            required: true
        }
    }
});

const INPUT = path.resolve(values.input);
const OUTPUT = path.resolve(values.output);

if (!existsSync(INPUT)) {
    console.error(`Input file "${INPUT}" does not exist.`);
    process.exit(2);
}

if (!statSync(INPUT).isFile()) {
    console.error(`Input path '${INPUT}' is not a file.`);
    process.exit(2);
}

mkdirSync(OUTPUT, { recursive: true });

await createClient({
    input: INPUT,
    output: {
        clean: false,
        path: OUTPUT,
        header: [
            '// @ts-nocheck',
            '/* eslint-disable */',
            '// This file was generated by @hey-api/openapi-ts. Do not edit.'
        ]
    },
    plugins: ['@hey-api/typescript', '@hey-api/sdk', '@hey-api/client-fetch']
});

console.log(OUTPUT);
