// This file was generated by logging-schema/codegen. Do not edit manually.
// Run `just gen-log-models` to regenerate.

import { z } from 'zod';

// ─── ApplicationStarted ──────────────────────────────────────────────────

export const ApplicationStartedSchema = z.object({
	host: z.string(),
	port: z.number().int()
});

export type ApplicationStartedPayload = z.infer<typeof ApplicationStartedSchema>;

const _APPLICATION_STARTED_META = {
	eventName: 'application.started',
	body: 'Application started'
} as const;

export type ApplicationStarted = {
	readonly $meta: typeof _APPLICATION_STARTED_META;
	readonly $payload: ApplicationStartedPayload;
};

export function applicationStarted(payload: ApplicationStartedPayload): ApplicationStarted {
	return {
		$meta: _APPLICATION_STARTED_META,
		$payload: payload
	};
}

// ─── ApplicationStopping ──────────────────────────────────────────────────

export const ApplicationStoppingSchema = z.object({});

export type ApplicationStoppingPayload = z.infer<typeof ApplicationStoppingSchema>;

const _APPLICATION_STOPPING_META = {
	eventName: 'application.stopping',
	body: 'Application stopping'
} as const;

export type ApplicationStopping = {
	readonly $meta: typeof _APPLICATION_STOPPING_META;
	readonly $payload: ApplicationStoppingPayload;
};

export function applicationStopping(payload: ApplicationStoppingPayload): ApplicationStopping {
	return {
		$meta: _APPLICATION_STOPPING_META,
		$payload: payload
	};
}

// ─── BackendCallCompleted ──────────────────────────────────────────────────

export const BackendCallCompletedSchema = z.object({
	operation_id: z.string(),
	status_code: z.number().int(),
	duration_ms: z.number(),
	request_id: z.string().optional()
});

export type BackendCallCompletedPayload = z.infer<typeof BackendCallCompletedSchema>;

const _BACKEND_CALL_COMPLETED_META = {
	eventName: 'bff.backend_call.completed',
	body: 'Backend API call completed'
} as const;

export type BackendCallCompleted = {
	readonly $meta: typeof _BACKEND_CALL_COMPLETED_META;
	readonly $payload: BackendCallCompletedPayload;
};

export function backendCallCompleted(payload: BackendCallCompletedPayload): BackendCallCompleted {
	return {
		$meta: _BACKEND_CALL_COMPLETED_META,
		$payload: payload
	};
}

// ─── HttpRequestCompleted ──────────────────────────────────────────────────

export const HttpRequestCompletedSchema = z.object({
	method: z.string(),
	path: z.string(),
	status_code: z.number().int(),
	duration_ms: z.number(),
	request_id: z.string().optional()
});

export type HttpRequestCompletedPayload = z.infer<typeof HttpRequestCompletedSchema>;

const _HTTP_REQUEST_COMPLETED_META = {
	eventName: 'http.request.completed',
	body: 'HTTP request completed'
} as const;

export type HttpRequestCompleted = {
	readonly $meta: typeof _HTTP_REQUEST_COMPLETED_META;
	readonly $payload: HttpRequestCompletedPayload;
};

export function httpRequestCompleted(payload: HttpRequestCompletedPayload): HttpRequestCompleted {
	return {
		$meta: _HTTP_REQUEST_COMPLETED_META,
		$payload: payload
	};
}

// ─── HttpRequestReceived ──────────────────────────────────────────────────

export const HttpRequestReceivedSchema = z.object({
	method: z.string(),
	path: z.string(),
	request_id: z.string().optional()
});

export type HttpRequestReceivedPayload = z.infer<typeof HttpRequestReceivedSchema>;

const _HTTP_REQUEST_RECEIVED_META = {
	eventName: 'http.request.received',
	body: 'HTTP request received'
} as const;

export type HttpRequestReceived = {
	readonly $meta: typeof _HTTP_REQUEST_RECEIVED_META;
	readonly $payload: HttpRequestReceivedPayload;
};

export function httpRequestReceived(payload: HttpRequestReceivedPayload): HttpRequestReceived {
	return {
		$meta: _HTTP_REQUEST_RECEIVED_META,
		$payload: payload
	};
}

export type LogEvent =
	| ApplicationStarted
	| ApplicationStopping
	| BackendCallCompleted
	| HttpRequestCompleted
	| HttpRequestReceived;
