// This file was generated by logging-schema/codegen. Do not edit manually.
// Run `just gen-log-models` to regenerate.

import { z } from 'zod';

// ─── ApplicationStarted ──────────────────────────────────────────────────

export const ApplicationStartedSchema = z.object({
    host: z.string(),
    port: z.number().int()
});

export type ApplicationStartedPayload = z.infer<typeof ApplicationStartedSchema>;

const _APPLICATION_STARTED_META = {
    eventName: 'application.started',
    body: 'Application started'
} as const;

export type ApplicationStarted = {
    readonly $meta: typeof _APPLICATION_STARTED_META;
    readonly $payload: ApplicationStartedPayload;
};

export function applicationStarted(payload: ApplicationStartedPayload): ApplicationStarted {
    return {
        $meta: _APPLICATION_STARTED_META,
        $payload: payload
    };
}

// ─── ApplicationStopping ──────────────────────────────────────────────────

export const ApplicationStoppingSchema = z.object({});

export type ApplicationStoppingPayload = z.infer<typeof ApplicationStoppingSchema>;

const _APPLICATION_STOPPING_META = {
    eventName: 'application.stopping',
    body: 'Application stopping'
} as const;

export type ApplicationStopping = {
    readonly $meta: typeof _APPLICATION_STOPPING_META;
    readonly $payload: ApplicationStoppingPayload;
};

export function applicationStopping(payload: ApplicationStoppingPayload): ApplicationStopping {
    return {
        $meta: _APPLICATION_STOPPING_META,
        $payload: payload
    };
}

// ─── BackendCallCompleted ──────────────────────────────────────────────────

export const BackendCallCompletedSchema = z.object({
    operation_id: z.string(),
    status_code: z.number().int(),
    duration_ms: z.number(),
    request_id: z.string().optional()
});

export type BackendCallCompletedPayload = z.infer<typeof BackendCallCompletedSchema>;

const _BACKEND_CALL_COMPLETED_META = {
    eventName: 'bff.backend_call.completed',
    body: 'Backend API call completed'
} as const;

export type BackendCallCompleted = {
    readonly $meta: typeof _BACKEND_CALL_COMPLETED_META;
    readonly $payload: BackendCallCompletedPayload;
};

export function backendCallCompleted(payload: BackendCallCompletedPayload): BackendCallCompleted {
    return {
        $meta: _BACKEND_CALL_COMPLETED_META,
        $payload: payload
    };
}

// ─── HttpRequestCompleted ──────────────────────────────────────────────────

export const HttpRequestCompletedSchema = z.object({
    method: z.string(),
    path: z.string(),
    status_code: z.number().int(),
    duration_ms: z.number(),
    request_id: z.string().optional()
});

export type HttpRequestCompletedPayload = z.infer<typeof HttpRequestCompletedSchema>;

const _HTTP_REQUEST_COMPLETED_META = {
    eventName: 'http.request.completed',
    body: 'HTTP request completed'
} as const;

export type HttpRequestCompleted = {
    readonly $meta: typeof _HTTP_REQUEST_COMPLETED_META;
    readonly $payload: HttpRequestCompletedPayload;
};

export function httpRequestCompleted(payload: HttpRequestCompletedPayload): HttpRequestCompleted {
    return {
        $meta: _HTTP_REQUEST_COMPLETED_META,
        $payload: payload
    };
}

// ─── HttpRequestReceived ──────────────────────────────────────────────────

export const HttpRequestReceivedSchema = z.object({
    method: z.string(),
    path: z.string(),
    request_id: z.string().optional()
});

export type HttpRequestReceivedPayload = z.infer<typeof HttpRequestReceivedSchema>;

const _HTTP_REQUEST_RECEIVED_META = {
    eventName: 'http.request.received',
    body: 'HTTP request received'
} as const;

export type HttpRequestReceived = {
    readonly $meta: typeof _HTTP_REQUEST_RECEIVED_META;
    readonly $payload: HttpRequestReceivedPayload;
};

export function httpRequestReceived(payload: HttpRequestReceivedPayload): HttpRequestReceived {
    return {
        $meta: _HTTP_REQUEST_RECEIVED_META,
        $payload: payload
    };
}

// ─── ImageBothDimensionsSet ──────────────────────────────────────────────────

export const ImageBothDimensionsSetSchema = z.object({
    url: z.string().optional(),
    height: z.string(),
    width: z.string()
});

export type ImageBothDimensionsSetPayload = z.infer<typeof ImageBothDimensionsSetSchema>;

const _IMAGE_BOTH_DIMENSIONS_SET_META = {
    eventName: 'image.both_dimensions_set',
    body: 'Both image dimensions are set, the aspect ratio may be distorted'
} as const;

export type ImageBothDimensionsSet = {
    readonly $meta: typeof _IMAGE_BOTH_DIMENSIONS_SET_META;
    readonly $payload: ImageBothDimensionsSetPayload;
};

export function imageBothDimensionsSet(
    payload: ImageBothDimensionsSetPayload
): ImageBothDimensionsSet {
    return {
        $meta: _IMAGE_BOTH_DIMENSIONS_SET_META,
        $payload: payload
    };
}

// ─── ValidatorNotUnsignedInt ──────────────────────────────────────────────────

export const ValidatorNotUnsignedIntSchema = z.object({
    origin: z.string(),
    value: z.string(),
    default_value: z.number().optional()
});

export type ValidatorNotUnsignedIntPayload = z.infer<typeof ValidatorNotUnsignedIntSchema>;

const _VALIDATOR_NOT_UNSIGNED_INT_META = {
    eventName: 'validator.not_unsigned_int',
    body: 'Value is not an unsigned int, using the default value'
} as const;

export type ValidatorNotUnsignedInt = {
    readonly $meta: typeof _VALIDATOR_NOT_UNSIGNED_INT_META;
    readonly $payload: ValidatorNotUnsignedIntPayload;
};

export function validatorNotUnsignedInt(
    payload: ValidatorNotUnsignedIntPayload
): ValidatorNotUnsignedInt {
    return {
        $meta: _VALIDATOR_NOT_UNSIGNED_INT_META,
        $payload: payload
    };
}

// ─── ZonedDateTimeMismatchedContexts ──────────────────────────────────────────────────

export const ZonedDateTimeMismatchedContextsSchema = z.object({
    start_utc: z.string(),
    end_utc: z.string(),
    start_kind: z.string(),
    end_kind: z.string(),
    start_time_zone: z.string(),
    start_locale: z.string(),
    end_time_zone: z.string(),
    end_locale: z.string(),
    format: z.string()
});

export type ZonedDateTimeMismatchedContextsPayload = z.infer<
    typeof ZonedDateTimeMismatchedContextsSchema
>;

const _ZONED_DATE_TIME_MISMATCHED_CONTEXTS_META = {
    eventName: 'zoned_date_time.mismatched_contexts',
    body: 'Date range formatted with mismatched contexts, using the start context'
} as const;

export type ZonedDateTimeMismatchedContexts = {
    readonly $meta: typeof _ZONED_DATE_TIME_MISMATCHED_CONTEXTS_META;
    readonly $payload: ZonedDateTimeMismatchedContextsPayload;
};

export function zonedDateTimeMismatchedContexts(
    payload: ZonedDateTimeMismatchedContextsPayload
): ZonedDateTimeMismatchedContexts {
    return {
        $meta: _ZONED_DATE_TIME_MISMATCHED_CONTEXTS_META,
        $payload: payload
    };
}

export type LogEvent =
    | ApplicationStarted
    | ApplicationStopping
    | BackendCallCompleted
    | HttpRequestCompleted
    | HttpRequestReceived
    | ImageBothDimensionsSet
    | ValidatorNotUnsignedInt
    | ZonedDateTimeMismatchedContexts;

export type BrowserLogEvent =
    ImageBothDimensionsSet | ValidatorNotUnsignedInt | ZonedDateTimeMismatchedContexts;

export const BROWSER_EVENT_PARSERS: Readonly<
    Record<string, (payload: unknown) => BrowserLogEvent | undefined>
> = {
    'image.both_dimensions_set': (payload) => {
        const result = ImageBothDimensionsSetSchema.safeParse(payload);
        return result.success ? imageBothDimensionsSet(result.data) : undefined;
    },

    'validator.not_unsigned_int': (payload) => {
        const result = ValidatorNotUnsignedIntSchema.safeParse(payload);
        return result.success ? validatorNotUnsignedInt(result.data) : undefined;
    },

    'zoned_date_time.mismatched_contexts': (payload) => {
        const result = ZonedDateTimeMismatchedContextsSchema.safeParse(payload);
        return result.success ? zonedDateTimeMismatchedContexts(result.data) : undefined;
    }
};
