services:
  backend:
    build:
      context: ../backend
      target: dev
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
