services:
  postgres:
    image: postgres:18.4-alpine3.24
    container_name: postgres-${ENVIRONMENT}
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10

volumes:
  postgres_data:
