# This file was generated by logging-schema/codegen. Do not edit manually.
# Run `just gen-log-models` to regenerate.

from typing import ClassVar
from typing import final

from backend.logging._base import LogEventBase


@final
class ApplicationStarted(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "application.started"
    LOG_BODY: ClassVar[str] = "Application started"
    host: str
    port: int


@final
class ApplicationStopping(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "application.stopping"
    LOG_BODY: ClassVar[str] = "Application stopping"


@final
class BackendCallCompleted(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "bff.backend_call.completed"
    LOG_BODY: ClassVar[str] = "Backend API call completed"
    operation_id: str
    status_code: int
    duration_ms: float
    request_id: str | None = None


@final
class HttpRequestCompleted(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "http.request.completed"
    LOG_BODY: ClassVar[str] = "HTTP request completed"
    method: str
    path: str
    status_code: int
    duration_ms: float
    request_id: str | None = None


@final
class HttpRequestReceived(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "http.request.received"
    LOG_BODY: ClassVar[str] = "HTTP request received"
    method: str
    path: str
    request_id: str | None = None


type LogEvent = (
    ApplicationStarted | ApplicationStopping | BackendCallCompleted | HttpRequestCompleted | HttpRequestReceived
)
