# This file was generated by logging-schema/codegen. Do not edit manually.
# Run `just gen-log-models` to regenerate.

from typing import ClassVar
from typing import final

from backend.logging._base import LogEventBase


@final
class ApplicationStarted(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "application.started"
    LOG_BODY: ClassVar[str] = "Application started"
    host: str
    port: int


@final
class ApplicationStopping(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "application.stopping"
    LOG_BODY: ClassVar[str] = "Application stopping"


@final
class BackendCallCompleted(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "bff.backend_call.completed"
    LOG_BODY: ClassVar[str] = "Backend API call completed"
    operation_id: str
    status_code: int
    duration_ms: float
    request_id: str | None = None


@final
class HttpRequestCompleted(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "http.request.completed"
    LOG_BODY: ClassVar[str] = "HTTP request completed"
    method: str
    path: str
    status_code: int
    duration_ms: float
    request_id: str | None = None


@final
class HttpRequestReceived(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "http.request.received"
    LOG_BODY: ClassVar[str] = "HTTP request received"
    method: str
    path: str
    request_id: str | None = None


@final
class ImageBothDimensionsSet(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "image.both_dimensions_set"
    LOG_BODY: ClassVar[str] = "Both image dimensions are set, the aspect ratio may be distorted"
    url: str | None = None
    height: str
    width: str


@final
class ValidatorNotUnsignedInt(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "validator.not_unsigned_int"
    LOG_BODY: ClassVar[str] = "Value is not an unsigned int, using the default value"
    origin: str
    value: str
    default_value: float | None = None


@final
class ZonedDateTimeMismatchedContexts(LogEventBase):
    LOG_EVENT_NAME: ClassVar[str] = "zoned_date_time.mismatched_contexts"
    LOG_BODY: ClassVar[str] = "Date range formatted with mismatched contexts, using the start context"
    start_utc: str
    end_utc: str
    start_kind: str
    end_kind: str
    start_time_zone: str
    start_locale: str
    end_time_zone: str
    end_locale: str
    format: str


type LogEvent = (
    ApplicationStarted
    | ApplicationStopping
    | BackendCallCompleted
    | HttpRequestCompleted
    | HttpRequestReceived
    | ImageBothDimensionsSet
    | ValidatorNotUnsignedInt
    | ZonedDateTimeMismatchedContexts
)
