name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.project-part }}-${{ matrix.command }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - check
          - test
        project-part:
          - frontend
          - backend

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install ${{ matrix.project-part }} project dependencies
        run: nix develop --command just ${{ matrix.project-part }}-init

      - name: Run ${{ matrix.project-part }} ${{ matrix.command }}
        run: nix develop --command just ${{ matrix.project-part }}-${{ matrix.command }}
