name: validate-api-client

on:
  pull_request:
  workflow_dispatch:

jobs:
  generated-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Initialize development environment 
        run: nix develop --command just init-ci

      - name: Generate OpenAPI schema
        working-directory: "backend"
        env:
          CI_TMP_DIR: ${{ runner.temp }}
        run: nix develop --command uv run scripts/dump-fast-api.py

      - name: Generate frontend client
        working-directory: "frontend"
        env:
          CI_TMP_DIR: ${{ runner.temp }}
        run: nix develop --command node scripts/gen-types.js --temp

      - name: Compare generated frontend client
        run: diff -ru frontend/src/generated "$RUNNER_TEMP/frontend/generated"
