name: validate-api-client

on:
  pull_request:
  workflow_dispatch:

jobs:
  generated-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Initialize development environment 
        run: nix develop --command just init-ci

      - name: Generate OpenAPI schema
        working-directory: "backend"
        run: nix develop --command 
             uv run scripts/dump-fast-api.py 
              -o ../temp/openapi/api.json 
              -g

      - name: Generate frontend client
        working-directory: "frontend"
        run: nix develop --command 
             node /scripts/gen-types.js 
              -i ../temp/openapi/api.json 
              -o ../temp/client 
              -g

      - name: Compare generated OpenAPI schema
        run: diff -u generated/api.json temp/openapi/api.json

      - name: Compare generated frontend client
        run: diff -ru frontend/src/generated temp/client
